# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kSlider = QtWidgets.QSlider(self.centralwidget)
        self.kSlider.setGeometry(QtCore.QRect(80, 180, 160, 22))
        self.kSlider.setMinimum(1)
        self.kSlider.setMaximum(6)
        self.kSlider.setProperty("value", 1)
        self.kSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kSlider.setObjectName("kSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 90, 47, 16))
        self.label.setObjectName("label")
        self.archivoBuscado = QtWidgets.QLineEdit(self.centralwidget)
        self.archivoBuscado.setGeometry(QtCore.QRect(130, 90, 261, 20))
        self.archivoBuscado.setObjectName("archivoBuscado")
        self.botonBuscarArchivo = QtWidgets.QPushButton(self.centralwidget)
        self.botonBuscarArchivo.setGeometry(QtCore.QRect(410, 90, 75, 23))
        self.botonBuscarArchivo.setObjectName("botonBuscarArchivo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 121, 31))
        self.label_2.setObjectName("label_2")
        self.valoresK = QtWidgets.QLabel(self.centralwidget)
        self.valoresK.setGeometry(QtCore.QRect(80, 210, 171, 31))
        self.valoresK.setObjectName("valoresK")
        self.botonAleatorio = QtWidgets.QPushButton(self.centralwidget)
        self.botonAleatorio.setGeometry(QtCore.QRect(80, 300, 75, 23))
        self.botonAleatorio.setObjectName("botonAleatorio")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 201, 21))
        self.label_3.setObjectName("label_3")
        self.botonHeuristica = QtWidgets.QPushButton(self.centralwidget)
        self.botonHeuristica.setGeometry(QtCore.QRect(210, 300, 75, 23))
        self.botonHeuristica.setObjectName("botonHeuristica")
        """ MainWindow.setCentralWidget(self.centralwidget) """
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        """ MainWindow.setStatusBar(self.statusbar) """

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        """ MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow")) """
        self.label.setText(_translate("MainWindow", "Archivo:"))
        self.botonBuscarArchivo.setText(_translate("MainWindow", "Buscar"))
        self.label_2.setText(_translate("MainWindow", "Cantidad de K"))
        self.valoresK.setText(_translate("MainWindow", "Valor actual: 1"))
        self.botonAleatorio.setText(_translate("MainWindow", "Aleatoria"))
        self.label_3.setText(_translate("MainWindow", "Inicialización de los clusters:"))
        self.botonHeuristica.setText(_translate("MainWindow", "Heurística"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
